FROM zenithar/openstack-base
MAINTAINER Thibault NORMAND <me@zenithar.org>

RUN apt-get install -y ceilometer-api ceilometer-collector ceilometer-agent-central \
    ceilometer-agent-notification ceilometer-alarm-evaluator ceilometer-alarm-notifier \
    python-ceilometerclient
