#!/bin/bash

set -e

ZNC_USER=$1
ZNC_PASS=$2

# /opt/znc/state is expected to be bind-mounted into the container
ZNC_ROOT="/opt/znc/state"

# create the configs/ dir if it doesn't exist
if [ ! -d ${ZNC_ROOT}/configs ]; then
    mkdir -p ${ZNC_ROOT}/configs
fi;

# create the znc.conf file if it doesn't exist
CONFIG_FILE=${ZNC_ROOT}/configs/znc.conf
if [ ! -e $CONFIG_FILE ]; then

# exit if there's no znc.conf but user and password were not provided
if [ $# -lt 2 ]; then
    echo "Usage: $0 <USER> <PASSWORD>"
    exit 1
fi;

# https://github.com/znc/znc/blob/master/src/User.cpp#L266
ZNC_SALT="$(dd if=/dev/urandom bs=16c count=1 | md5sum | awk '{print $1}')"
ZNC_HASH="$(echo -n ${ZNC_PASS}${ZNC_SALT} | sha256sum | awk '{print $1}')"

cat<<EOF > /etc/oident.conf
default {
    default {
        allow spoof
        allow spoof_all
        allow spoof_privport
        allow random
        allow random_numeric
        allow numeric
        allow hide
    }
}

EOF

cat<<EOF > ${CONFIG_FILE}

Version = 1.2

<Listener l>
  Port = 6697
  IPv4 = true
  IPv6 = false
  SSL = true
</Listener>
LoadModule = webadmin
LoadModule = identfile

<User $ZNC_USER>
  Pass       = sha256#$ZNC_HASH#$ZNC_SALT
  Admin      = true
  Nick       = $ZNC_USER
  AltNick    = ${ZNC_USER}_
  Ident      = $ZNC_USER
  Buffer     = 50
  AutoClearChanBuffer = true
  ChanModes  = +stn

  LoadModule = chansaver
  LoadModule = webadmin

  <Network freenode>
    LoadModule = chansaver
    LoadModule = nickserv

    Server     = chat.freenode.net +6667

  </Network>
</User>

EOF

fi;
chown -R znc:znc ${ZNC_ROOT}
exec sudo -u znc znc -r -f -d ${ZNC_ROOT}
