FROM zenithar/openstack-base
MAINTAINER Thibault NORMAND <me@zenithar.org>

RUN apt-get install -y nova-novncproxy novnc nova-api nova-ajax-console-proxy nova-cert \
        nova-conductor nova-consoleauth nova-doc nova-scheduler python-novaclient nova-network
